version: '3.8'

services:
  airdrop-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GNOSIS_RPC_URL=${GNOSIS_RPC_URL:-https://rpc.gnosischain.com}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - SECRET_PREIMAGE=${SECRET_PREIMAGE}
      - SECRET_PREIMAGES=${SECRET_PREIMAGES}
      - AIRDROP_AMOUNT_WEI=${AIRDROP_AMOUNT_WEI:-1000000000000000000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/airdrop/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - airdrop-network

networks:
  airdrop-network:
    driver: bridge
