[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildArgs = { BUILDKIT_INLINE_CACHE = "1" }

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/airdrop/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
